spring.datasource.url=jdbc:h2:file:./data/libridb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Gestione dello schema (DDL)
spring.jpa.hibernate.ddl-auto=update

# Abilita la console grafica
spring.h2.console.enabled=true