spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./data/libreriadb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.settings.web-allow-others=true

# Gestione dello schema (DDL) - impostato su "none" per evitare modifiche automatiche al database, sennò fare update
spring.jpa.hibernate.ddl-auto=none

# 2. Forza Spring Boot a cercare e inizializzare i file SQL (schema.sql e data.sql)
spring.sql.init.mode=always

# 3. (Opzionale) Se vuoi vedere in console le query che esegue Spring all'avvio
logging.level.org.springframework.jdbc.datasource.init=DEBUG

# Configurazione di SpringDoc OpenAPI
springdoc.api-docs.path=/api-docs

# 1. Mostra le query SQL generali (comprese le DDL)
spring.jpa.show-sql=true