spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./data/libreriadb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Gestione dello schema (DDL)
spring.jpa.hibernate.ddl-auto=update

# Configurazione di SpringDoc OpenAPI
springdoc.api-docs.path=/api-docs

# 1. Mostra le query SQL generali (comprese le DDL)
spring.jpa.show-sql=true